

[project]
name = "sfarkxtc-windows-repo-tests"
version = "0.2"
authors = [
  { name="Ben Fisher", email="shinerainseven@gmail.com" },
]
license = "GPL-3.0"
license-files = ["../COPYING"]
description = "Tests for sfarkxtc"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "shinerainsevenlib",
]

[project.optional-dependencies]
dev = [
    "pylint",
    "ruff",
]


[project.urls]
Homepage = "https://github.com/moltenform/sfarkxtc-windows"
Issues = "https://github.com/moltenform/sfarkxtc-windows/issues"

[tool.ruff]
line-length = 95
indent-width = 4
target-version = "py38"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.ruff.lint]

[tool.pylint.'MESSAGES CONTROL']

[tool.shinerainsevenlib]
config_collection_legacy = 1
pylint_import_suggested_other_settings = 1
rufflint_import_suggested_other_settings = 1

rufflint_ignore = [
    'S101', # asserts instead of assertTrue
    "F541", # unneeded fstrings ok
    "SIM905", # 'a|b|c'.split('|') is ok
    "B904", # raise from
]

pylint_ignore = [
    "C0304",
    "W1309",
    "W3101",
    "C0302",
    "R0801",
]

pylint_specific_ignore_containing = [
    # skip this - we don't care about it for Bucket
    "E1101: Instance of 'Bucket' has no",
    # skip this - we don't care about it for fixtures
    "W0621: Redefining name 'fixture_",
    "Access to a protected member _get of",
    "Access to a protected member _get_id of",
]

rufflint_specific_ignore_containing = [
]

format_skip_if_path_contains = [
    '/OUTSIDE/'
]

[tool.yapf]

# styles: google, pep8, yapf, facebook
based_on_style = "facebook"
spaces_before_comment = 1
split_before_logical_operator = false
column_limit = 95
indent_width = 4
